### PR TITLE
Major path overhaul

### PR DESCRIPTION
**Pull request by dodomorandi**
I really appreciated your work on porting the old building system to CMake. I think that is a big step forward in order to improve the project maintainability.

Said that, I decided to perform a path overhaul, moving every source file inside a `src` directory. I also splitted the list of files that must be compiled in a single `CMakeLists.txt` for each directory, in order to make things more easy to maintain.

There are many things left to do, but this is can be a starting point. Leave me your feedbacks!

### CODE REVIEW

**Comment by ceeac** [comment]
While I appreciate your effort, I think it is best not to have a large difference between the original simutrans repository and this one. So please suggest your path changes (sans the CMake stuff) to the simutrans forum [here](https://forum.simutrans.com/index.php/board,33.0.html) first.

**Comment by dodomorandi** [comment]
In this case the problem in the original branch is that this should require much more effort that with CMake. On the other hand, you are right: if it is not easy to introduce a complete new build system, it will be even harder to change paths. What do you think if keep improving this branch whilst you send a PR for the _basic_ (yeah, it is totally not _basic_, but let me call it in this way) CMake port?

Said that, if you have suggestions about the work that should be done, I will be happy to put a checklist in the first message.

**Comment by ceeac** [comment]
I already did send a patch a couple of weeks ago, but iirc it was shot down because they want to keep the Makefile and VS project file based build systems, and also because CMake does not work too well on MinGW (I have not tested that myself). Also I'm not sure whether CMake 3.8 is available on all OSes Simutrans supports, so a direct replacement of all build systems is not feasible anyway.

**Comment by dodomorandi** [comment]
But CMake is designed exactly to produce VS project files on Windows... Honestly I never used CMake to cross-compile using mingw, but I don't think it would be troublesome. If you think you need some support for you patch (in the sense that I can cross-compile and test the results on windows) just let me know. I sent you this PR because I was thinking that your work would have been accepted in some time, what you are saying is a bit sad.

**Pull request closed without merging**
